apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "financehub.fullname" . }}
  namespace: {{ .Values.namespaceOverride }}
  labels:
    {{- include "financehub.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "financehub.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "financehub.fullname" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          {{- if .Values.envFromSecret }}
          envFrom:
            - secretRef:
                name: {{ .Values.envFromSecret }}
          {{- end }}
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 20
            periodSeconds: 20
            failureThreshold: 6
          resources:
            {{- toYaml .Values.resources | nindent 12 }}

