apiVersion: v1
kind: Service
metadata:
  name: {{ include "financehub.fullname" . }}
  namespace: {{ .Values.namespaceOverride }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "financehub.fullname" . }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80

