apiVersion: v1
kind: Service
metadata:
  name: {{ include "financehub.fullname" . }}
  namespace: {{ .Values.namespaceOverride }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "financehub.fullname" . }}
  ports:
    - name: http
      port: {{ .Values.service.port }}                           # cluster-facing (80)
      targetPort: {{ .Values.service.targetPort | default 8080 }} # container port (8080)
